"""Edit profile pic path in User model

Revision ID: a5989dbf64e8
Revises: 40be9b0a20cf
Create Date: 2022-01-19 22:46:33.044038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5989dbf64e8'
down_revision = '40be9b0a20cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_column('users', 'profile_pic_pah')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_pah', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
