"""Create profile columns

Revision ID: ee5bab919f4c
Revises: f56e0dac1b5b
Create Date: 2022-01-19 20:17:22.217230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5bab919f4c'
down_revision = 'f56e0dac1b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_pah', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_pah')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
